name = cw_core
description = Core assets, items, nodes, and crafting for Cube_World
author = Gerold55
version = 1.0
license = MIT

# Usually core mods load before others, so min deps:
depends =

# If you use sounds, groups, or textures from those:
optional_depends = player_api, creative, 3d_armor
